### ISSUE TITLE
I think your account is expired

### ISSUE THREAD

**Issue by jaydip430** [K-E-N-W-A-Y/Skillshare-DL#13]
Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 74, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

**Comment by patusi** [comment]
Greetings
Dear @K-E-N-W-A-Y KENWAY i think your account expired, and i saw same erro that @jaydip430 wrote down here. could you please provide another one and fix it? or tell us the method for changing the cookies. Thank you sincerely.
warm regards

**Comment by naimeh461** [comment]
Please fix the problem.

**Comment by calvinhobbes23** [comment]
If anyone has an account, please place the credentials in a text file and upload here:

https://tinyurl.com/yedpzx59
password = skillshare
