### ISSUE TITLE
Failed to read video ID from data

### ISSUE THREAD

**Issue by clydesantiago** [K-E-N-W-A-Y/Skillshare-DL#16]
It's not working

Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 74, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

**Comment by minhducbg** [comment]
try this [https://github.com/calvinhobbes23/Skillshare-DL](url)
