### ISSUE TITLE
Unable to download new skillshare classes.

### ISSUE THREAD

**Issue by debanikray** [K-E-N-W-A-Y/Skillshare-DL#18]
Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 66, in download_course_by_class_id
    for u in data['_embedded']['units']['_embedded']['units']:
TypeError: list indices must be integers or slices, not str

**Comment by 1ndurani** [comment]
Yes , some courses only makes the error

ex : https://skl.sh/3hPmfaR

This course not working ,but other courses works well

how to fix this problem ?

**Comment by Gutha-Vamsi-Krishna** [comment]
For newer courses try this 
https://colab.research.google.com/github/vamsigutha/Skillshare-DL/blob/master/Skillshare.ipynb
forked this repo and modified
