### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by papercrwn** [K-E-N-W-A-Y/Skillshare-DL#2]
Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 33, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 29, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_class_id
    data = self.fetch_course_data_by_class_id(class_id=class_id)
  File "/root/.Skillshare-DL/skillshare.py", line 69, in fetch_course_data_by_class_id
    assert res.status_code == 200, 'Fetch error, code == {}'.format(res.status_code)
AssertionError: Fetch error, code == 403

**Comment by K-E-N-W-A-Y** [comment]
can you share url so i can test it.

**Comment by papercrwn** [comment]
try this one
https://www.skillshare.com/classes/Painting-Light-and-Shadow-The-Basics-for-Portraits-and-Characters/1574976051?via=user-profile

but actually its happened to every link I've tried

**Comment by K-E-N-W-A-Y** [comment]
Oh yes, i also got 403 errors. It looks like they are blocking requests. I'll try to fix but can't guarantee fix or give ETA.

**Comment by K-E-N-W-A-Y** [comment]
fixed

**Comment by Iulipartenie** [comment]
Thank you very much! You are Awesome!

**Comment by papercrwn** [comment]
Thanks a lot! You saved my day 👍
