### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by saifeealii** [K-E-N-W-A-Y/Skillshare-DL#9]
not working anymore, please fix it, will be thankful

Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 74, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

**Comment by K-E-N-W-A-Y** [comment]
i don't have live skillshare account anymore. so if anyone having problems please use @calvinhobbes23 [fork repo](https://colab.research.google.com/github/calvinhobbes23/Skillshare-DL/blob/master/Skillshare_DL_%5BKENWAY%5D.ipynb)
